# Generated by Django 5.2.5 on 2025-09-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Online payment', 'Online payment')], default='Cash on delivery', max_length=20),
        ),
    ]
